-- MySQL Script generated by MySQL Workbench
-- Sun Sep 14 17:00:24 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gurama
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gurama
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gurama` DEFAULT CHARACTER SET utf8mb4 ;
USE `gurama` ;

-- -----------------------------------------------------
-- Table `gurama`.`tipo_documento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gurama`.`tipo_documento` ;

CREATE TABLE IF NOT EXISTS `gurama`.`tipo_documento` (
  `t_doc` VARCHAR(10) NOT NULL COMMENT 'PK Código único del tipo de documento (ejemplo: CC, TI, NIT).',
  `desc_doc` VARCHAR(20) NOT NULL COMMENT 'Nombre o descripción completa del documento (ejemplo: Cédula de ciudadanía, Tarjeta de identidad, etc.).',
  PRIMARY KEY (`t_doc`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `gurama`.`Rol_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gurama`.`Rol_usuario` ;

CREATE TABLE IF NOT EXISTS `gurama`.`Rol_usuario` (
  `id_rol_usuario` VARCHAR(20) NOT NULL COMMENT 'PK Identificador único del rol.',
  `nombre_rol` VARCHAR(45) NOT NULL COMMENT 'Nombre del rol que tendrá el usuario (ejemplo: Cliente o Administrador).',
  PRIMARY KEY (`id_rol_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gurama`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gurama`.`usuario` ;

CREATE TABLE IF NOT EXISTS `gurama`.`usuario` (
  `id_usuario` VARCHAR(15) NOT NULL COMMENT 'PK Identificador único de cada usuario (Numero de identificacion).',
  `nom_1` VARCHAR(50) NOT NULL COMMENT 'Primer nombre del usuario.',
  `nom_2` VARCHAR(50) NULL DEFAULT NULL COMMENT 'Segundo nombre del usuario (opcional).',
  `ape_1` VARCHAR(50) NOT NULL COMMENT 'Primer apellido del usuario.',
  `ape_2` VARCHAR(50) NULL DEFAULT NULL COMMENT 'Segundo apellido del usuario (opcional).',
  `correo` VARCHAR(40) NOT NULL COMMENT 'Dirección de correo electrónico del usuario (Solo una registrada).',
  `telefono` BIGINT(10) NOT NULL COMMENT 'Número de teléfono o celular del usuario.',
  `Contraseña` VARCHAR(25) NOT NULL COMMENT 'contraseña alfanumerica con la que el usuario podra ingresar al sistema',
  `codigo` VARCHAR(10) NULL COMMENT 'Se le pide al administrador cuando trata de iniciar sesión',
  `t_doc` VARCHAR(10) NOT NULL COMMENT 'PK_FK Relación con el tipo de documento que posee el usuario (CC, CE, TI).',
  `id_rol_usuario` VARCHAR(20) NOT NULL COMMENT 'PK_FK Relación con el rol del usuario (ejemplo: cliente/admin).',
  PRIMARY KEY (`id_usuario`, `t_doc`, `id_rol_usuario`),
  INDEX `fk_usuario_tipo_documento_idx` (`t_doc` ASC) VISIBLE,
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC) VISIBLE,
  INDEX `fk_usuario_Rol_usuario1_idx` (`id_rol_usuario` ASC) VISIBLE,
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_tipo_documento`
    FOREIGN KEY (`t_doc`)
    REFERENCES `gurama`.`tipo_documento` (`t_doc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_Rol_usuario1`
    FOREIGN KEY (`id_rol_usuario`)
    REFERENCES `gurama`.`Rol_usuario` (`id_rol_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `gurama`.`tipo_pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gurama`.`tipo_pedido` ;

CREATE TABLE IF NOT EXISTS `gurama`.`tipo_pedido` (
  `id_tipo` VARCHAR(4) NOT NULL COMMENT 'PK Identificador único del tipo de pedido.',
  `tipo_pedido` VARCHAR(10) NOT NULL COMMENT 'Nombre del tipo (ejemplo: estándar, personalizado).',
  PRIMARY KEY (`id_tipo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `gurama`.`pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gurama`.`pedido` ;

CREATE TABLE IF NOT EXISTS `gurama`.`pedido` (
  `id_pedido` INT(4) NOT NULL COMMENT 'PK Identificador unico del pedido',
  `fecha` DATETIME NOT NULL COMMENT 'Fecha y hora en que se realizó el pedido.',
  `estado` VARCHAR(20) NOT NULL COMMENT 'Estado actual del pedido (ejemplo: pendiente, pagado, enviado).',
  `id_usuario` VARCHAR(15) NOT NULL COMMENT 'FK Usuario que realizó el pedido.\n',
  `tipo_pedido_id_tipo` VARCHAR(4) NOT NULL COMMENT 'PK_FK relacion que indica el tipo de pedido (normal, personalizado).',
  PRIMARY KEY (`id_pedido`, `tipo_pedido_id_tipo`),
  INDEX `fk_pedido_usuario1_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `fk_pedido_tipo_pedido1_idx` (`tipo_pedido_id_tipo` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `gurama`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_tipo_pedido1`
    FOREIGN KEY (`tipo_pedido_id_tipo`)
    REFERENCES `gurama`.`tipo_pedido` (`id_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `gurama`.`estado_pago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gurama`.`estado_pago` ;

CREATE TABLE IF NOT EXISTS `gurama`.`estado_pago` (
  `id_estado` VARCHAR(3) NOT NULL COMMENT 'PK Identificador único del estado del pago.',
  `estado_pago` TINYINT(1) NOT NULL COMMENT 'Estado del pago (ejemplo: aprobado, rechazado, pendiente).\n',
  PRIMARY KEY (`id_estado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `gurama`.`metodo_pago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gurama`.`metodo_pago` ;

CREATE TABLE IF NOT EXISTS `gurama`.`metodo_pago` (
  `id_met_pago` VARCHAR(3) NOT NULL COMMENT 'PK Identificador unico del metodo de pago',
  `nombr_metodo` VARCHAR(30) NOT NULL COMMENT 'Forma de pago utilizada, ejemplo: tarjeta, transferencia (en este caso sera simulada).',
  PRIMARY KEY (`id_met_pago`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `gurama`.`Factura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gurama`.`Factura` ;

CREATE TABLE IF NOT EXISTS `gurama`.`Factura` (
  `id_factura` INT(6) NOT NULL COMMENT 'PK Identificador único de la factura.\n',
  `num_factura` INT NOT NULL AUTO_INCREMENT COMMENT 'numero de la factura emitida (10, 245, 30, 1002...)',
  `fecha_emision` DATETIME NOT NULL COMMENT 'Fecha de emisión de la factura.',
  `subtotal` DECIMAL NOT NULL COMMENT 'Suma de los precios de los productos en el pedido, sin incluir impuestos ni descuentos.',
  `total_factura` DECIMAL NOT NULL COMMENT 'Valor total facturado.\n',
  `id_pedido` INT(4) NOT NULL COMMENT 'PK_FK Relaciona el pedido realizado con la factura',
  `id_estado` VARCHAR(3) NOT NULL COMMENT 'FK relaciona el estado de pago con la factura (cuando esta se emite el estado cambia)',
  `id_met_pago` VARCHAR(3) NOT NULL COMMENT 'PK_FK Relaciona el metodo de pago usado con la factura',
  PRIMARY KEY (`id_pedido`, `id_met_pago`, `id_factura`),
  INDEX `fk_Factura_pedido1_idx` (`id_pedido` ASC) VISIBLE,
  INDEX `fk_Factura_estado_pago1_idx` (`id_estado` ASC) VISIBLE,
  INDEX `fk_Factura_metodo_pago1_idx` (`id_met_pago` ASC) VISIBLE,
  CONSTRAINT `fk_Factura_pedido1`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `gurama`.`pedido` (`id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Factura_estado_pago1`
    FOREIGN KEY (`id_estado`)
    REFERENCES `gurama`.`estado_pago` (`id_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Factura_metodo_pago1`
    FOREIGN KEY (`id_met_pago`)
    REFERENCES `gurama`.`metodo_pago` (`id_met_pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `gurama`.`Categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gurama`.`Categoria` ;

CREATE TABLE IF NOT EXISTS `gurama`.`Categoria` (
  `idCategoria` INT NOT NULL COMMENT 'PK Identificador único de la categoría.\n',
  `nombre_c` VARCHAR(45) NOT NULL COMMENT 'Nombre de la categoría (ejemplo: llaveros, amigurumis, sábanas).\n',
  `descripcion` VARCHAR(65) NULL COMMENT 'Breve explicación de la categoría (opcional).',
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gurama`.`producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gurama`.`producto` ;

CREATE TABLE IF NOT EXISTS `gurama`.`producto` (
  `id_producto` VARCHAR(3) NOT NULL COMMENT 'PK Identificador único del producto.',
  `nom_producto` VARCHAR(20) NOT NULL COMMENT 'Nombre del producto.',
  `precio_unitario` INT(10) NOT NULL COMMENT 'Precio de venta por unidad.',
  `Descripcion` VARCHAR(45) NOT NULL COMMENT 'Información general del producto.',
  `stock_minimo` INT NOT NULL COMMENT 'Cantidad mínima que debe haber en inventario para no generar alerta.\n',
  `Color` VARCHAR(25) NULL COMMENT 'Contiene el color del producto personalizado',
  `Talla` VARCHAR(25) NULL COMMENT 'Contiene la talla del producto personalizado',
  `Tamañol` VARCHAR(25) NULL COMMENT 'Contiene el tamaño del producto personalizado',
  `id_Categoria` INT NOT NULL COMMENT 'FK Identificador de la categoria del producto, viene de la tabla categoria',
  PRIMARY KEY (`id_producto`),
  INDEX `fk_producto_Categoria1_idx` (`id_Categoria` ASC) VISIBLE,
  CONSTRAINT `fk_producto_Categoria1`
    FOREIGN KEY (`id_Categoria`)
    REFERENCES `gurama`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `gurama`.`datalle_pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gurama`.`datalle_pedido` ;

CREATE TABLE IF NOT EXISTS `gurama`.`datalle_pedido` (
  `id_detalle` VARCHAR(4) NOT NULL COMMENT 'PK Identificador único del detalle del pedido.\n',
  `Cantidad` VARCHAR(45) NOT NULL COMMENT 'Número de unidades de un producto dentro del pedido.\n',
  `descripcion` VARCHAR(30) NOT NULL COMMENT 'Información extra (ejemplo: color, tamaño, tela en productos personalizados).',
  `id_pedido` INT(4) NOT NULL COMMENT 'PK_FK Relación con el pedido al que pertenece el detalle.\n',
  `id_producto` VARCHAR(3) NOT NULL COMMENT 'PK_FK Relación con el producto al que pertenece el detalle.',
  PRIMARY KEY (`id_detalle`, `id_pedido`, `id_producto`),
  INDEX `fk_datalle_pedido_pedido1_idx` (`id_pedido` ASC) VISIBLE,
  INDEX `fk_datalle_pedido_producto1_idx` (`id_producto` ASC) VISIBLE,
  CONSTRAINT `fk_datalle_pedido_pedido1`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `gurama`.`pedido` (`id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_datalle_pedido_producto1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `gurama`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `gurama`.`tipo_movimiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gurama`.`tipo_movimiento` ;

CREATE TABLE IF NOT EXISTS `gurama`.`tipo_movimiento` (
  `id_m` VARCHAR(5) NOT NULL COMMENT 'PK identificador unico del tipo de movimiento',
  `nom_movimiento` VARCHAR(11) NOT NULL COMMENT 'nombre del tipo de movimieto (entrada o salida)',
  PRIMARY KEY (`id_m`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `gurama`.`inventario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gurama`.`inventario` ;

CREATE TABLE IF NOT EXISTS `gurama`.`inventario` (
  `cantidad_actual` INT NOT NULL COMMENT 'Stock total disponible en ese momento.\n',
  `ultima_actualizacion` DATETIME NOT NULL COMMENT 'Fecha y hora de la última modificación en inventario.\n',
  `id_producto` VARCHAR(3) NOT NULL COMMENT 'PK_FK relaciona un producto con el inventario',
  PRIMARY KEY (`id_producto`),
  INDEX `fk_inventario_producto1_idx` (`id_producto` ASC) VISIBLE,
  CONSTRAINT `fk_inventario_producto1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `gurama`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gurama`.`movimiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gurama`.`movimiento` ;

CREATE TABLE IF NOT EXISTS `gurama`.`movimiento` (
  `id_movimiento` VARCHAR(3) NOT NULL COMMENT 'PK Identificador único del movimiento.\n',
  `cantidad_m` INT(5) NOT NULL COMMENT 'Cantidad de productos en el movimiento (entrada o salida).\n',
  `fecha_m` DATETIME NOT NULL COMMENT 'Fecha en que se registró el movimiento.\n',
  `observacion` VARCHAR(80) NULL DEFAULT NULL COMMENT 'Nota descriptiva (ejemplo: compra de proveedor, venta a cliente).\n',
  `tipo_movimiento_id_m` VARCHAR(5) NOT NULL COMMENT 'PK_FK relaciona al movimieto con un tipo de movimiento (entrada/salida)',
  `inventario_id_producto` VARCHAR(3) NOT NULL COMMENT 'PK_FK relaciona al movimieto con un producto del inventario',
  `id_usuario` VARCHAR(15) NOT NULL COMMENT 'FK relaciona al movimieto con el usuario (admin) que lo realiza',
  PRIMARY KEY (`id_movimiento`, `tipo_movimiento_id_m`, `inventario_id_producto`),
  INDEX `fk_movimiento_tipo_movimiento1_idx` (`tipo_movimiento_id_m` ASC) VISIBLE,
  INDEX `fk_movimiento_inventario1_idx` (`inventario_id_producto` ASC) VISIBLE,
  INDEX `fk_movimiento_usuario1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_movimiento_tipo_movimiento1`
    FOREIGN KEY (`tipo_movimiento_id_m`)
    REFERENCES `gurama`.`tipo_movimiento` (`id_m`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movimiento_inventario1`
    FOREIGN KEY (`inventario_id_producto`)
    REFERENCES `gurama`.`inventario` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movimiento_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `gurama`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `gurama`.`Clasificación`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gurama`.`Clasificación` ;

CREATE TABLE IF NOT EXISTS `gurama`.`Clasificación` (
  `id_Clasificación` INT NOT NULL COMMENT 'PK Identificador único de la clasificación.\n',
  `Nom_c` VARCHAR(45) NOT NULL COMMENT 'Nombre de la clasificación (ejemplo: oferta, más vendido, promoción).',
  PRIMARY KEY (`id_Clasificación`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gurama`.`producto_clasificacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gurama`.`producto_clasificacion` ;

CREATE TABLE IF NOT EXISTS `gurama`.`producto_clasificacion` (
  `id_Clasificación` INT NOT NULL COMMENT 'PK_FK relaciona la clasificacion a un producto',
  `id_producto` VARCHAR(3) NOT NULL COMMENT 'PK_FK relaciona al producto con su respectiva clasificacion',
  PRIMARY KEY (`id_Clasificación`, `id_producto`),
  INDEX `fk_Clasificación_has_producto_Clasificación1_idx` (`id_Clasificación` ASC) VISIBLE,
  INDEX `fk_producto_clasificacion_producto1_idx` (`id_producto` ASC) VISIBLE,
  CONSTRAINT `fk_Clasificación_has_producto_Clasificación1`
    FOREIGN KEY (`id_Clasificación`)
    REFERENCES `gurama`.`Clasificación` (`id_Clasificación`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_clasificacion_producto1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `gurama`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
